#!/usr/bin/env python3
# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``rosbridge/codecs/robot_interfaces.py`` from ROS interface files.

Source definitions live under ``dimos/agents/rosbridge/srv/robot_interfaces/``.
Refresh them from the robot when interfaces change::

    ssh daxbot-104
    source ~/daxbot_nav_ws/install/setup.bash
    ros2 interface show robot_interfaces/msg/SlamStatus
    ros2 interface show robot_interfaces/msg/NavStatus
    ros2 interface show robot_interfaces/action/NavigateToPose

Then update the matching ``.msg`` / ``.action`` files and run::

    cd ~/Projects/dimos
    .venv/bin/python scripts/generate_robot_interfaces_codecs.py
"""

from __future__ import annotations

import re
from pathlib import Path

from py_rosbridge.codegen import generate

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFINITIONS_DIR = REPO_ROOT / "dimos" / "agents" / "rosbridge" / "srv" / "robot_interfaces"
OUTPUT_PATH = REPO_ROOT / "dimos" / "agents" / "rosbridge" / "codecs" / "robot_interfaces.py"

LICENSE_HEADER = """# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by scripts/generate_robot_interfaces_codecs.py — do not edit by hand.
"""

# Map nested ROS types to py_rosbridge built-in codec modules.
EXTERNAL_TYPES: dict[str, tuple[str, str]] = {
    "builtin_interfaces/msg/Duration": ("builtin_interfaces", "Duration"),
    "builtin_interfaces/msg/Time": ("builtin_interfaces", "Time"),
    "geometry_msgs/msg/Point": ("geometry_msgs", "Point"),
    "geometry_msgs/msg/Pose": ("geometry_msgs", "Pose"),
    "geometry_msgs/msg/PoseStamped": ("geometry_msgs", "PoseStamped"),
    "geometry_msgs/msg/Quaternion": ("geometry_msgs", "Quaternion"),
    "std_msgs/msg/Header": ("std_msgs", "Header"),
}


def _definition_paths() -> list[Path]:
    paths = sorted(DEFINITIONS_DIR.glob("msg/*.msg"))
    paths.extend(sorted(DEFINITIONS_DIR.glob("action/*.action")))
    if not paths:
        raise FileNotFoundError(f"No .msg/.action files under {DEFINITIONS_DIR}")
    return paths


def _postprocess_generated_body(body: str) -> str:
    # codegen emits relative imports for external modules; use py_rosbridge built-ins.
    body = re.sub(r"^from \. import \w+ as \w+\n", "", body, flags=re.MULTILINE)
    body = body.replace(
        "from py_rosbridge.cdr import FieldSpec, MessageCodec",
        "from py_rosbridge.cdr import FieldSpec, MessageCodec\n"
        "from py_rosbridge.codecs import TYPE_REGISTRY as BUILTIN_TYPE_REGISTRY\n"
        "from py_rosbridge.codecs import builtin_interfaces, geometry_msgs, std_msgs",
        1,
    )
    body = body.replace(
        "TYPE_REGISTRY = {",
        "TYPE_REGISTRY = {\n    **BUILTIN_TYPE_REGISTRY,",
        1,
    )
    return body


def render_output() -> str:
    generated = generate(
        _definition_paths(),
        package="robot_interfaces",
        external_types=EXTERNAL_TYPES,
    )
    # Strip the default codegen banner; we add license + module docstring instead.
    generated = re.sub(
        r"^# Generated by rosbridge-codegen\. Do not edit by hand\.\n+",
        "",
        generated,
        count=1,
    )
    body = _postprocess_generated_body(generated)
    return f"{LICENSE_HEADER}\n{body}"


def main() -> int:
    paths = _definition_paths()
    output = render_output()
    OUTPUT_PATH.write_text(output)
    print(f"Wrote {OUTPUT_PATH}")
    print("Sources:")
    for path in paths:
        print(f"  - {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
