# Generated by rosbridge-codegen. Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass, field

from py_rosbridge.cdr import FieldSpec, MessageCodec


@dataclass
class ExecutePickTaskRequest:
    workspace_name: str = ''
    workspace_color: str = ''
    sku_name: str = ''
    sku_color: str = ''

class ExecutePickTaskRequestCodec(MessageCodec):
    message_type = ExecutePickTaskRequest
    ros_type = 'dax_dimos_interfaces/srv/ExecutePickTask/Request'
    fields = (
        FieldSpec(name='workspace_name', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='workspace_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='sku_name', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='sku_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class ExecutePickTaskResponse:
    command: str = ''
    status: str = ''
    success: bool = False
    failure_reason: str = ''
    result_json: str = ''

class ExecutePickTaskResponseCodec(MessageCodec):
    message_type = ExecutePickTaskResponse
    ros_type = 'dax_dimos_interfaces/srv/ExecutePickTask/Response'
    fields = (
        FieldSpec(name='command', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='success', type_name='bool', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='failure_reason', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_json', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class GoToWorkspaceRequest:
    workspace_name: str = ''
    workspace_color: str = ''

class GoToWorkspaceRequestCodec(MessageCodec):
    message_type = GoToWorkspaceRequest
    ros_type = 'dax_dimos_interfaces/srv/GoToWorkspace/Request'
    fields = (
        FieldSpec(name='workspace_name', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='workspace_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class GoToWorkspaceResponse:
    command: str = ''
    status: str = ''
    success: bool = False
    failure_reason: str = ''
    result_json: str = ''

class GoToWorkspaceResponseCodec(MessageCodec):
    message_type = GoToWorkspaceResponse
    ros_type = 'dax_dimos_interfaces/srv/GoToWorkspace/Response'
    fields = (
        FieldSpec(name='command', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='success', type_name='bool', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='failure_reason', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_json', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class PickSkuRequest:
    workspace_name: str = ''
    workspace_color: str = ''
    sku_name: str = ''
    sku_color: str = ''
    side: str = ''

class PickSkuRequestCodec(MessageCodec):
    message_type = PickSkuRequest
    ros_type = 'dax_dimos_interfaces/srv/PickSku/Request'
    fields = (
        FieldSpec(name='workspace_name', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='workspace_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='sku_name', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='sku_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='side', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class PickSkuResponse:
    command: str = ''
    status: str = ''
    success: bool = False
    failure_reason: str = ''
    result_json: str = ''

class PickSkuResponseCodec(MessageCodec):
    message_type = PickSkuResponse
    ros_type = 'dax_dimos_interfaces/srv/PickSku/Response'
    fields = (
        FieldSpec(name='command', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='success', type_name='bool', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='failure_reason', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_json', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class RunDemoRequest:
    workspace_color: str = ''
    sku_color: str = ''

class RunDemoRequestCodec(MessageCodec):
    message_type = RunDemoRequest
    ros_type = 'dax_dimos_interfaces/srv/RunDemo/Request'
    fields = (
        FieldSpec(name='workspace_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='sku_color', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class RunDemoResponse:
    command: str = ''
    status: str = ''
    success: bool = False
    failure_reason: str = ''
    result_json: str = ''

class RunDemoResponseCodec(MessageCodec):
    message_type = RunDemoResponse
    ros_type = 'dax_dimos_interfaces/srv/RunDemo/Response'
    fields = (
        FieldSpec(name='command', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='success', type_name='bool', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='failure_reason', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_json', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class TriggerRequest:
    pass

class TriggerRequestCodec(MessageCodec):
    message_type = TriggerRequest
    ros_type = 'dax_dimos_interfaces/srv/Trigger/Request'
    fields = (
    )


@dataclass
class TriggerResponse:
    command: str = ''
    status: str = ''
    success: bool = False
    failure_reason: str = ''
    result_json: str = ''

class TriggerResponseCodec(MessageCodec):
    message_type = TriggerResponse
    ros_type = 'dax_dimos_interfaces/srv/Trigger/Response'
    fields = (
        FieldSpec(name='command', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='success', type_name='bool', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='failure_reason', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_json', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


TYPE_REGISTRY = {
    'dax_dimos_interfaces/srv/ExecutePickTask/Request': ExecutePickTaskRequestCodec,
    'dax_dimos_interfaces/srv/ExecutePickTask/Response': ExecutePickTaskResponseCodec,
    'dax_dimos_interfaces/srv/GoToWorkspace/Request': GoToWorkspaceRequestCodec,
    'dax_dimos_interfaces/srv/GoToWorkspace/Response': GoToWorkspaceResponseCodec,
    'dax_dimos_interfaces/srv/PickSku/Request': PickSkuRequestCodec,
    'dax_dimos_interfaces/srv/PickSku/Response': PickSkuResponseCodec,
    'dax_dimos_interfaces/srv/RunDemo/Request': RunDemoRequestCodec,
    'dax_dimos_interfaces/srv/RunDemo/Response': RunDemoResponseCodec,
    'dax_dimos_interfaces/srv/Trigger/Request': TriggerRequestCodec,
    'dax_dimos_interfaces/srv/Trigger/Response': TriggerResponseCodec,
}

ExecutePickTaskRequestCodec.type_registry = TYPE_REGISTRY
ExecutePickTaskResponseCodec.type_registry = TYPE_REGISTRY
GoToWorkspaceRequestCodec.type_registry = TYPE_REGISTRY
GoToWorkspaceResponseCodec.type_registry = TYPE_REGISTRY
PickSkuRequestCodec.type_registry = TYPE_REGISTRY
PickSkuResponseCodec.type_registry = TYPE_REGISTRY
RunDemoRequestCodec.type_registry = TYPE_REGISTRY
RunDemoResponseCodec.type_registry = TYPE_REGISTRY
TriggerRequestCodec.type_registry = TYPE_REGISTRY
TriggerResponseCodec.type_registry = TYPE_REGISTRY

__all__ = ['ExecutePickTaskRequest', 'ExecutePickTaskResponse', 'GoToWorkspaceRequest', 'GoToWorkspaceResponse', 'PickSkuRequest', 'PickSkuResponse', 'RunDemoRequest', 'RunDemoResponse', 'TriggerRequest', 'TriggerResponse', 'ExecutePickTaskRequestCodec', 'ExecutePickTaskResponseCodec', 'GoToWorkspaceRequestCodec', 'GoToWorkspaceResponseCodec', 'PickSkuRequestCodec', 'PickSkuResponseCodec', 'RunDemoRequestCodec', 'RunDemoResponseCodec', 'TriggerRequestCodec', 'TriggerResponseCodec', 'TYPE_REGISTRY']
