# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by scripts/generate_robot_interfaces_codecs.py — do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass, field

from py_rosbridge.cdr import FieldSpec, MessageCodec
from py_rosbridge.codecs import TYPE_REGISTRY as BUILTIN_TYPE_REGISTRY
from py_rosbridge.codecs import builtin_interfaces, geometry_msgs, std_msgs



@dataclass
class NavStatus:
    timestamp: float = 0.0
    status_code: int = 0
    description: str = ''
    uuid: bytes = b''

class NavStatusCodec(MessageCodec):
    message_type = NavStatus
    ros_type = 'robot_interfaces/msg/NavStatus'
    fields = (
        FieldSpec(name='timestamp', type_name='float64', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status_code', type_name='int32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='description', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='uuid', type_name='uint8', is_array=True, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class SlamStatus:
    header: std_msgs.Header = field(default_factory=lambda: std_msgs.Header())
    status: str = ''
    current_map_name: str = ''
    pose: geometry_msgs.Pose = field(default_factory=lambda: geometry_msgs.Pose())
    score: float = 0.0
    process: float = 0.0
    expect_time: float = 0.0
    relocated: bool = False
    reloc_used_time: float = 0.0
    opt_works_remain: int = 0
    angle: float = 0.0

class SlamStatusCodec(MessageCodec):
    message_type = SlamStatus
    ros_type = 'robot_interfaces/msg/SlamStatus'
    fields = (
        FieldSpec(name='header', type_name='std_msgs/msg/Header', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='status', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='current_map_name', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='pose', type_name='geometry_msgs/msg/Pose', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='score', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='process', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='expect_time', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='relocated', type_name='bool', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='reloc_used_time', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='opt_works_remain', type_name='int16', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='angle', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class NavigateToPoseGoal:
    pose: geometry_msgs.PoseStamped = field(default_factory=lambda: geometry_msgs.PoseStamped())
    behavior_tree: str = ''

class NavigateToPoseGoalCodec(MessageCodec):
    message_type = NavigateToPoseGoal
    ros_type = 'robot_interfaces/action/NavigateToPose/Goal'
    fields = (
        FieldSpec(name='pose', type_name='geometry_msgs/msg/PoseStamped', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='behavior_tree', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class NavigateToPoseResult:
    result_code: int = 0
    result_message: str = ''
    result_pose: geometry_msgs.PoseStamped = field(default_factory=lambda: geometry_msgs.PoseStamped())

class NavigateToPoseResultCodec(MessageCodec):
    message_type = NavigateToPoseResult
    ros_type = 'robot_interfaces/action/NavigateToPose/Result'
    fields = (
        FieldSpec(name='result_code', type_name='int32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_message', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='result_pose', type_name='geometry_msgs/msg/PoseStamped', is_array=False, array_size=None, upper_bound=None, default=None),
    )


@dataclass
class NavigateToPoseFeedback:
    current_pose: geometry_msgs.PoseStamped = field(default_factory=lambda: geometry_msgs.PoseStamped())
    navigation_time: builtin_interfaces.Duration = field(default_factory=lambda: builtin_interfaces.Duration())
    estimated_time_remaining: builtin_interfaces.Duration = field(default_factory=lambda: builtin_interfaces.Duration())
    distance_remaining: float = 0.0
    speed: float = 0.0
    navigation_state: int = 0
    navigation_state_description: str = ''
    uuid: bytes = b''

class NavigateToPoseFeedbackCodec(MessageCodec):
    message_type = NavigateToPoseFeedback
    ros_type = 'robot_interfaces/action/NavigateToPose/Feedback'
    fields = (
        FieldSpec(name='current_pose', type_name='geometry_msgs/msg/PoseStamped', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='navigation_time', type_name='builtin_interfaces/msg/Duration', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='estimated_time_remaining', type_name='builtin_interfaces/msg/Duration', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='distance_remaining', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='speed', type_name='float32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='navigation_state', type_name='int32', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='navigation_state_description', type_name='string', is_array=False, array_size=None, upper_bound=None, default=None),
        FieldSpec(name='uuid', type_name='uint8', is_array=True, array_size=None, upper_bound=None, default=None),
    )


TYPE_REGISTRY = {
    **BUILTIN_TYPE_REGISTRY,
    'robot_interfaces/msg/NavStatus': NavStatusCodec,
    'robot_interfaces/msg/SlamStatus': SlamStatusCodec,
    'robot_interfaces/action/NavigateToPose/Goal': NavigateToPoseGoalCodec,
    'robot_interfaces/action/NavigateToPose/Result': NavigateToPoseResultCodec,
    'robot_interfaces/action/NavigateToPose/Feedback': NavigateToPoseFeedbackCodec,
}

NavStatusCodec.type_registry = TYPE_REGISTRY
SlamStatusCodec.type_registry = TYPE_REGISTRY
NavigateToPoseGoalCodec.type_registry = TYPE_REGISTRY
NavigateToPoseResultCodec.type_registry = TYPE_REGISTRY
NavigateToPoseFeedbackCodec.type_registry = TYPE_REGISTRY

__all__ = ['NavStatus', 'SlamStatus', 'NavigateToPoseGoal', 'NavigateToPoseResult', 'NavigateToPoseFeedback', 'NavStatusCodec', 'SlamStatusCodec', 'NavigateToPoseGoalCodec', 'NavigateToPoseResultCodec', 'NavigateToPoseFeedbackCodec', 'TYPE_REGISTRY']
